Fri Apr  4 03:40:55 2025 — Failed to send AppendEntries to node1: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50086: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-04-04T03:40:55.523656-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50086: Failed to connect to remote host: connect: Connection refused (61)"}"
>
Fri Apr  4 03:40:58 2025 — Failed to send AppendEntries to node1: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50086: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50086: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-04-04T03:40:58.531643-04:00"}"
>
Fri Apr  4 03:41:01 2025 — Failed to send AppendEntries to node1: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50086: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50086: Failed to connect to remote host: connect: Connection refused (61)", grpc_status:14, created_time:"2025-04-04T03:41:01.537457-04:00"}"
>
Fri Apr  4 03:41:04 2025 — Failed to send AppendEntries to node1: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50086: Failed to connect to remote host: connect: Connection refused (61)"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2025-04-04T03:41:04.545993-04:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:127.0.0.1:50086: Failed to connect to remote host: connect: Connection refused (61)"}"
>
